services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:17
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
    env_file:
      - .env

  redis:
    image: redis:7
    restart: always

  celery:
    build: .
    command: celery -A config.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A config.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

volumes:
  pg_data:
